[book]
title = "Data Structures and Algorithms"
authors = ["Robert Lawson, a little bit of the internet"]
description = "A book to explain about data structures and algorithms"
text-direction = "ltr"
language = "en"
multilingual = false

[rust]
edition = "2015"

[build]
build-dir = "s-and-a"
create-missing = false

[preprocessor.generate-summary]

[preprocessor.index]

[preprocessor.links]

[output.html.playground]
editable = true

[output.html.fold]
enable = false    

[output.html]

[output.html.search]
limit-results = 15
